// Add your portfolio items here. Keep newest or strongest works near the top.
// This file can be updated manually or with the local admin at http://127.0.0.1:8787/admin.html.

window.portfolioWorks = [
    {
        "title":  "【社群廣告】貓砂引流廣告",
        "year":  "2026",
        "category":  "social-ad",
        "categoryLabel":  "社群廣告",
        "role":  "企劃 / 拍攝 / 剪輯",
        "tools":  "",
        "description":  "設計HOOK讓觀眾對影片產生好奇，直擊痛點讓觀眾對產品有興趣",
        "videoUrl":  "https://youtube.com/shorts/ORJzL4OtSP4?feature=share",
        "embedUrl":  "https://www.youtube.com/embed/ORJzL4OtSP4",
        "thumbnailUrl":  "assets/covers/2026-06-08-152817.png",
        "thumbnailFit":  "contain",
        "thumbnailPositionX":  50,
        "thumbnailPositionY":  50,
        "isSample":  false
    },
    {
        "title":  "【短影音作品】清潔公司老闆 - 恐怖排水孔怎麼處理",
        "year":  "2026",
        "category":  "short",
        "categoryLabel":  "短影音",
        "role":  "影片剪輯 / 字幕 / 社群短影音",
        "tools":  "",
        "description":  "著重吸引力、節奏與社群觀看體驗",
        "videoUrl":  "https://www.instagram.com/reel/DYRlRqbD1s8/",
        "embedUrl":  "",
        "thumbnailUrl":  "assets/covers/689540104_17940783333212396_3856789125628256322_n-20260608150044.jpg",
        "thumbnailFit":  "contain",
        "thumbnailPositionX":  48,
        "thumbnailPositionY":  54,
        "isSample":  false
    },
    {
        "title":  "寵物品牌 - 全系列罐頭攻略",
        "year":  "2026",
        "category":  "social-ad",
        "categoryLabel":  "社群廣告",
        "role":  "影片剪輯 / 字幕 / 社群廣告",
        "tools":  "",
        "description":  "以攻略型內容整理寵物品牌全系列罐頭特色，協助觀眾快速理解產品差異。",
        "videoUrl":  "https://youtube.com/shorts/meNCJ469rBU?feature=share",
        "embedUrl":  "https://www.youtube.com/embed/meNCJ469rBU",
        "thumbnailUrl":  "assets/covers/cover.jpg",
        "thumbnailFit":  "cover",
        "thumbnailPositionX":  50,
        "thumbnailPositionY":  63,
        "isSample":  false
    },
    {
        "title":  "寵物品牌 - 拓印相框感性影片",
        "year":  "2026",
        "category":  "social-ad",
        "categoryLabel":  "社群廣告",
        "role":  "影片剪輯 / 字幕 / 社群廣告",
        "tools":  "",
        "description":  "以感性敘事呈現寵物拓印相框，強化情感記憶與產品價值。",
        "videoUrl":  "https://www.instagram.com/reel/DMPCaSWv74E/",
        "embedUrl":  "",
        "thumbnailUrl":  "assets/covers/520710063_18367420744147115_4609283519474633192_n-20260608145616.jpg",
        "thumbnailFit":  "cover",
        "thumbnailPositionX":  50,
        "thumbnailPositionY":  74,
        "isSample":  false
    },
    {
        "title":  "【旅遊節目】法國人酷來甘比亞玩搭乘大眾運輸自由行",
        "year":  "2024",
        "category":  "youtube",
        "categoryLabel":  "YT長片",
        "role":  "長片剪輯 / 雙語字幕 / 影片包裝",
        "tools":  "",
        "description":  "YouTube 長片作品，整理旅遊與人物互動素材，維持故事節奏與觀看流暢度",
        "videoUrl":  "https://www.youtube.com/watch?v=hD1WBR24W3Y",
        "embedUrl":  "https://www.youtube.com/embed/hD1WBR24W3Y",
        "thumbnailUrl":  "https://i.ytimg.com/vi/hD1WBR24W3Y/hqdefault.jpg",
        "isSample":  false
    },
    {
        "title":  "【競賽節目】 台灣消防隊體能競賽",
        "year":  "2023",
        "category":  "youtube",
        "categoryLabel":  "YT長片",
        "role":  "長片剪輯 / 影片後製",
        "tools":  "Adobe Premiere, After Effect",
        "description":  "YouTube 長片作品，針對長篇素材進行敘事整理、節奏剪輯與觀看體驗優化",
        "videoUrl":  "https://www.youtube.com/watch?v=_Dypo4KP07A",
        "embedUrl":  "https://www.youtube.com/embed/_Dypo4KP07A",
        "thumbnailUrl":  "https://i.ytimg.com/vi/_Dypo4KP07A/hqdefault.jpg",
        "isSample":  false
    },
    {
        "title":  "【競賽節目】 世足神預測「臺尋國際手足球比賽」法國直接預約冠軍？！",
        "year":  "2022",
        "category":  "youtube",
        "categoryLabel":  "YT長片",
        "role":  "長片剪輯 / 字幕 / 影片包裝",
        "tools":  "",
        "description":  "YouTube 長片作品，有效處理 8 機素材，將長時間的競賽透過剪輯優化觀看體驗",
        "videoUrl":  "https://www.youtube.com/watch?v=ekCYwRmCJCc",
        "embedUrl":  "https://www.youtube.com/embed/ekCYwRmCJCc",
        "thumbnailUrl":  "https://i.ytimg.com/vi/ekCYwRmCJCc/hqdefault.jpg",
        "isSample":  false
    },
    {
        "title":  "【旅遊節目】身世之謎大公開「離開台灣到OO找生父」",
        "year":  "2024",
        "category":  "youtube",
        "categoryLabel":  "YT長片",
        "role":  "長片剪輯 / 字幕 / 影片包裝",
        "tools":  "",
        "description":  "YouTube 長片作品，整理人物故事與情緒段落，讓長片敘事更清楚並保留觀看節奏。",
        "videoUrl":  "https://www.youtube.com/watch?v=aiNDyJAtJgE",
        "embedUrl":  "https://www.youtube.com/embed/aiNDyJAtJgE",
        "thumbnailUrl":  "https://i.ytimg.com/vi/aiNDyJAtJgE/hqdefault.jpg",
        "isSample":  false
    },
    {
        "title":  "【公益短片】搜救犬無酬搜救的真相",
        "year":  "2026",
        "category":  "nonprofit",
        "categoryLabel":  "公益影片",
        "role":  "企劃 / 拍攝 / 影片剪輯",
        "tools":  "",
        "description":  "公益社群影片作品，協助議題以更容易被觀看與分享的方式傳達",
        "videoUrl":  "https://www.instagram.com/reel/DONMxmLEnp3/?utm_source=ig_web_copy_link\u0026igsh=NTc4MTIwNjQ2YQ==",
        "embedUrl":  "",
        "thumbnailUrl":  "assets/covers/2025_---EP1_COVER.jpg",
        "thumbnailFit":  "contain",
        "thumbnailPositionX":  50,
        "thumbnailPositionY":  50,
        "isSample":  false
    }
];